// Code generated by mockery v2.46.3. DO NOT EDIT.

package backtest

import mock "github.com/stretchr/testify/mock"

// MockUnsafeSessionServicerServer is an autogenerated mock type for the UnsafeSessionServicerServer type
type MockUnsafeSessionServicerServer struct {
	mock.Mock
}

// mustEmbedUnimplementedSessionServicerServer provides a mock function with given fields:
func (_m *MockUnsafeSessionServicerServer) mustEmbedUnimplementedSessionServicerServer() {
	_m.Called()
}

// NewMockUnsafeSessionServicerServer creates a new instance of MockUnsafeSessionServicerServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeSessionServicerServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeSessionServicerServer {
	mock := &MockUnsafeSessionServicerServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
