// Code generated by mockery v2.46.3. DO NOT EDIT.

package stream

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMessage is an autogenerated mock type for the Message type
type MockMessage struct {
	mock.Mock
}

// Call provides a mock function with given fields: ctx, key
func (_m *MockMessage) Call(ctx context.Context, key Dependency) (interface{}, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, Dependency) (interface{}, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, Dependency) interface{}); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, Dependency) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetID provides a mock function with given fields:
func (_m *MockMessage) GetID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetOrchestrationID provides a mock function with given fields:
func (_m *MockMessage) GetOrchestrationID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOrchestrationID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetOrchestrationStep provides a mock function with given fields:
func (_m *MockMessage) GetOrchestrationStep() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOrchestrationStep")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MustGet provides a mock function with given fields: key
func (_m *MockMessage) MustGet(key Dependency) interface{} {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for MustGet")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(Dependency) interface{}); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// ParsePayload provides a mock function with given fields: payload
func (_m *MockMessage) ParsePayload(payload interface{}) error {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for ParsePayload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RawPayload provides a mock function with given fields:
func (_m *MockMessage) RawPayload() []byte {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RawPayload")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// NewMockMessage creates a new instance of MockMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessage {
	mock := &MockMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
