linters:
  enable-all: true
  disable:
    - paralleltest
    - musttag
    - ireturn
    - testpackage
    - exportloopref
    - nosprintfhostport
    - err113
    - dupword
    - contextcheck
    - cyclop
    - lll
