repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      # - id: go-fmt
      # - id: go-vet
      # - id: go-imports
      # - id: go-cyclo
      # args: [-over=15]
      # - id: no-go-testing
      - id: golangci-lint
      # - id: go-critic
      - id: go-build
      - id: go-mod-tidy

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        name: lint with ruff
        args: [--fix]
      - id: ruff
        name: sort imports with ruff
        args: [--select, I, --fix]
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.4.20
    hooks:
      # Run the pip compile
      - id: pip-compile
        args: [requirements.in, -o, requirements.txt]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.384
    hooks:
      - id: pyright
