// Code generated by mockery v2.18.0. DO NOT EDIT.

package supplier

import (
	entity "github.com/lhjnilsson/foreverbull/pkg/finance/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockTrading is an autogenerated mock type for the Trading type
type MockTrading struct {
	mock.Mock
}

// GetOrders provides a mock function with given fields:
func (_m *MockTrading) GetOrders() ([]*entity.Order, error) {
	ret := _m.Called()

	var r0 []*entity.Order
	if rf, ok := ret.Get(0).(func() []*entity.Order); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPortfolio provides a mock function with given fields:
func (_m *MockTrading) GetPortfolio() (*entity.Portfolio, error) {
	ret := _m.Called()

	var r0 *entity.Portfolio
	if rf, ok := ret.Get(0).(func() *entity.Portfolio); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Portfolio)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockTrading interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockTrading creates a new instance of MockTrading. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockTrading(t mockConstructorTestingTNewMockTrading) *MockTrading {
	mock := &MockTrading{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
