// Code generated by mockery v2.46.3. DO NOT EDIT.

package supplier

import (
	finance "github.com/lhjnilsson/foreverbull/pkg/pb/finance"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockMarketdata is an autogenerated mock type for the Marketdata type
type MockMarketdata struct {
	mock.Mock
}

// GetAsset provides a mock function with given fields: symbol
func (_m *MockMarketdata) GetAsset(symbol string) (*finance.Asset, error) {
	ret := _m.Called(symbol)

	if len(ret) == 0 {
		panic("no return value specified for GetAsset")
	}

	var r0 *finance.Asset
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*finance.Asset, error)); ok {
		return rf(symbol)
	}
	if rf, ok := ret.Get(0).(func(string) *finance.Asset); ok {
		r0 = rf(symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*finance.Asset)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIndex provides a mock function with given fields: symbol
func (_m *MockMarketdata) GetIndex(symbol string) ([]*finance.Asset, error) {
	ret := _m.Called(symbol)

	if len(ret) == 0 {
		panic("no return value specified for GetIndex")
	}

	var r0 []*finance.Asset
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*finance.Asset, error)); ok {
		return rf(symbol)
	}
	if rf, ok := ret.Get(0).(func(string) []*finance.Asset); ok {
		r0 = rf(symbol)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*finance.Asset)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(symbol)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOHLC provides a mock function with given fields: symbol, start, end
func (_m *MockMarketdata) GetOHLC(symbol string, start time.Time, end *time.Time) ([]*finance.OHLC, error) {
	ret := _m.Called(symbol, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetOHLC")
	}

	var r0 []*finance.OHLC
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time, *time.Time) ([]*finance.OHLC, error)); ok {
		return rf(symbol, start, end)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time, *time.Time) []*finance.OHLC); ok {
		r0 = rf(symbol, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*finance.OHLC)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time, *time.Time) error); ok {
		r1 = rf(symbol, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockMarketdata creates a new instance of MockMarketdata. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMarketdata(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMarketdata {
	mock := &MockMarketdata{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
