// Code generated by mockery v2.46.3. DO NOT EDIT.

package socket

import mock "github.com/stretchr/testify/mock"

// MockOptionSetter is an autogenerated mock type for the OptionSetter type
type MockOptionSetter struct {
	mock.Mock
}

// SetOption provides a mock function with given fields: name, value
func (_m *MockOptionSetter) SetOption(name string, value interface{}) error {
	ret := _m.Called(name, value)

	if len(ret) == 0 {
		panic("no return value specified for SetOption")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(name, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockOptionSetter creates a new instance of MockOptionSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOptionSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOptionSetter {
	mock := &MockOptionSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
