// Code generated by mockery v2.18.0. DO NOT EDIT.

package pb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeIngestionServicerServer is an autogenerated mock type for the UnsafeIngestionServicerServer type
type MockUnsafeIngestionServicerServer struct {
	mock.Mock
}

// mustEmbedUnimplementedIngestionServicerServer provides a mock function with given fields:
func (_m *MockUnsafeIngestionServicerServer) mustEmbedUnimplementedIngestionServicerServer() {
	_m.Called()
}

type mockConstructorTestingTNewMockUnsafeIngestionServicerServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUnsafeIngestionServicerServer creates a new instance of MockUnsafeIngestionServicerServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUnsafeIngestionServicerServer(t mockConstructorTestingTNewMockUnsafeIngestionServicerServer) *MockUnsafeIngestionServicerServer {
	mock := &MockUnsafeIngestionServicerServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
