# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: foreverbull/strategy/strategy_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'foreverbull/strategy/strategy_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+foreverbull/strategy/strategy_service.proto\x12\x14\x66oreverbull.strategy\"\x14\n\x12RunStrategyRequest\"\x15\n\x13RunStrategyResponse2v\n\x10StrategyServicer\x12\x62\n\x0bRunStrategy\x12(.foreverbull.strategy.RunStrategyRequest\x1a).foreverbull.strategy.RunStrategyResponseB3Z1github.com/lhjnilsson/foreverbull/pkg/strategy/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'foreverbull.strategy.strategy_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z1github.com/lhjnilsson/foreverbull/pkg/strategy/pb'
  _globals['_RUNSTRATEGYREQUEST']._serialized_start=69
  _globals['_RUNSTRATEGYREQUEST']._serialized_end=89
  _globals['_RUNSTRATEGYRESPONSE']._serialized_start=91
  _globals['_RUNSTRATEGYRESPONSE']._serialized_end=112
  _globals['_STRATEGYSERVICER']._serialized_start=114
  _globals['_STRATEGYSERVICER']._serialized_end=232
# @@protoc_insertion_point(module_scope)
