// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: foreverbull/pb/service/service.proto

package service

import (
	finance "github.com/lhjnilsson/foreverbull/internal/pb/finance"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NamespaceRequestType int32

const (
	NamespaceRequestType_GET NamespaceRequestType = 0
	NamespaceRequestType_SET NamespaceRequestType = 1
)

// Enum value maps for NamespaceRequestType.
var (
	NamespaceRequestType_name = map[int32]string{
		0: "GET",
		1: "SET",
	}
	NamespaceRequestType_value = map[string]int32{
		"GET": 0,
		"SET": 1,
	}
)

func (x NamespaceRequestType) Enum() *NamespaceRequestType {
	p := new(NamespaceRequestType)
	*p = x
	return p
}

func (x NamespaceRequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NamespaceRequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_foreverbull_pb_service_service_proto_enumTypes[0].Descriptor()
}

func (NamespaceRequestType) Type() protoreflect.EnumType {
	return &file_foreverbull_pb_service_service_proto_enumTypes[0]
}

func (x NamespaceRequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NamespaceRequestType.Descriptor instead.
func (NamespaceRequestType) EnumDescriptor() ([]byte, []int) {
	return file_foreverbull_pb_service_service_proto_rawDescGZIP(), []int{0}
}

type ServiceInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceType string                      `protobuf:"bytes,1,opt,name=serviceType,proto3" json:"serviceType,omitempty"`
	Version     string                      `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Socket      *ServiceInfoResponse_Socket `protobuf:"bytes,3,opt,name=socket,proto3" json:"socket,omitempty"`
}

func (x *ServiceInfoResponse) Reset() {
	*x = ServiceInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foreverbull_pb_service_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfoResponse) ProtoMessage() {}

func (x *ServiceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foreverbull_pb_service_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfoResponse.ProtoReflect.Descriptor instead.
func (*ServiceInfoResponse) Descriptor() ([]byte, []int) {
	return file_foreverbull_pb_service_service_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceInfoResponse) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *ServiceInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceInfoResponse) GetSocket() *ServiceInfoResponse_Socket {
	if x != nil {
		return x.Socket
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task string `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foreverbull_pb_service_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_foreverbull_pb_service_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_foreverbull_pb_service_service_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *Request) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task  string  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Data  []byte  `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
	Error *string `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foreverbull_pb_service_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_foreverbull_pb_service_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_foreverbull_pb_service_service_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Response) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type Algorithm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath   string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Functions  []*Algorithm_Function  `protobuf:"bytes,2,rep,name=functions,proto3" json:"functions,omitempty"`
	Namespaces []*Algorithm_Namespace `protobuf:"bytes,3,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
}

func (x *Algorithm) Reset() {
	*x = Algorithm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foreverbull_pb_service_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Algorithm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Algorithm) ProtoMessage() {}

func (x *Algorithm) ProtoReflect() protoreflect.Message {
	mi := &file_foreverbull_pb_service_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Algorithm.ProtoReflect.Descriptor instead.
func (*Algorithm) Descriptor() ([]byte, []int) {
	return file_foreverbull_pb_service_service_proto_rawDescGZIP(), []int{3}
}

func (x *Algorithm) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Algorithm) GetFunctions() []*Algorithm_Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *Algorithm) GetNamespaces() []*Algorithm_Namespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type ConfigureExecutionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BrokerPort    int32                                 `protobuf:"varint,1,opt,name=brokerPort,proto3" json:"brokerPort,omitempty"`
	NamespacePort int32                                 `protobuf:"varint,2,opt,name=namespacePort,proto3" json:"namespacePort,omitempty"`
	DatabaseURL   string                                `protobuf:"bytes,3,opt,name=databaseURL,proto3" json:"databaseURL,omitempty"`
	Functions     []*ConfigureExecutionRequest_Function `protobuf:"bytes,4,rep,name=functions,proto3" json:"functions,omitempty"`
}

func (x *ConfigureExecutionRequest) Reset() {
	*x = ConfigureExecutionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foreverbull_pb_service_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureExecutionRequest) ProtoMessage() {}

func (x *ConfigureExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foreverbull_pb_service_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureExecutionRequest.ProtoReflect.Descriptor instead.
func (*ConfigureExecutionRequest) Descriptor() ([]byte, []int) {
	return file_foreverbull_pb_service_service_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigureExecutionRequest) GetBrokerPort() int32 {
	if x != nil {
		return x.BrokerPort
	}
	return 0
}

func (x *ConfigureExecutionRequest) GetNamespacePort() int32 {
	if x != nil {
		return x.NamespacePort
	}
	return 0
}

func (x *ConfigureExecutionRequest) GetDatabaseURL() string {
	if x != nil {
		return x.DatabaseURL
	}
	return ""
}

func (x *ConfigureExecutionRequest) GetFunctions() []*ConfigureExecutionRequest_Function {
	if x != nil {
		return x.Functions
	}
	return nil
}

type ConfigureExecutionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigureExecutionResponse) Reset() {
	*x = ConfigureExecutionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foreverbull_pb_service_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureExecutionResponse) ProtoMessage() {}

func (x *ConfigureExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foreverbull_pb_service_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureExecutionResponse.ProtoReflect.Descriptor instead.
func (*ConfigureExecutionResponse) Descriptor() ([]byte, []int) {
	return file_foreverbull_pb_service_service_proto_rawDescGZIP(), []int{5}
}

type WorkerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task      string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Symbols   []string               `protobuf:"bytes,3,rep,name=symbols,proto3" json:"symbols,omitempty"`
	Portfolio *finance.Portfolio     `protobuf:"bytes,4,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
}

func (x *WorkerRequest) Reset() {
	*x = WorkerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foreverbull_pb_service_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRequest) ProtoMessage() {}

func (x *WorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foreverbull_pb_service_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRequest.ProtoReflect.Descriptor instead.
func (*WorkerRequest) Descriptor() ([]byte, []int) {
	return file_foreverbull_pb_service_service_proto_rawDescGZIP(), []int{6}
}

func (x *WorkerRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *WorkerRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WorkerRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *WorkerRequest) GetPortfolio() *finance.Portfolio {
	if x != nil {
		return x.Portfolio
	}
	return nil
}

type WorkerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task   string           `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Orders []*finance.Order `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	Error  *string          `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *WorkerResponse) Reset() {
	*x = WorkerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foreverbull_pb_service_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerResponse) ProtoMessage() {}

func (x *WorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foreverbull_pb_service_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerResponse.ProtoReflect.Descriptor instead.
func (*WorkerResponse) Descriptor() ([]byte, []int) {
	return file_foreverbull_pb_service_service_proto_rawDescGZIP(), []int{7}
}

func (x *WorkerResponse) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *WorkerResponse) GetOrders() []*finance.Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *WorkerResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type NamespaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string               `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Type  NamespaceRequestType `protobuf:"varint,2,opt,name=type,proto3,enum=foreverbull.pb.service.NamespaceRequestType" json:"type,omitempty"`
	Value *structpb.Struct     `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
}

func (x *NamespaceRequest) Reset() {
	*x = NamespaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foreverbull_pb_service_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceRequest) ProtoMessage() {}

func (x *NamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foreverbull_pb_service_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceRequest.ProtoReflect.Descriptor instead.
func (*NamespaceRequest) Descriptor() ([]byte, []int) {
	return file_foreverbull_pb_service_service_proto_rawDescGZIP(), []int{8}
}

func (x *NamespaceRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *NamespaceRequest) GetType() NamespaceRequestType {
	if x != nil {
		return x.Type
	}
	return NamespaceRequestType_GET
}

func (x *NamespaceRequest) GetValue() *structpb.Struct {
	if x != nil {
		return x.Value
	}
	return nil
}

type NamespaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *structpb.Struct `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Error *string          `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
}

func (x *NamespaceResponse) Reset() {
	*x = NamespaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foreverbull_pb_service_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceResponse) ProtoMessage() {}

func (x *NamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foreverbull_pb_service_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceResponse.ProtoReflect.Descriptor instead.
func (*NamespaceResponse) Descriptor() ([]byte, []int) {
	return file_foreverbull_pb_service_service_proto_rawDescGZIP(), []int{9}
}

func (x *NamespaceResponse) GetValue() *structpb.Struct {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *NamespaceResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ServiceInfoResponse_Socket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *ServiceInfoResponse_Socket) Reset() {
	*x = ServiceInfoResponse_Socket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foreverbull_pb_service_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInfoResponse_Socket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfoResponse_Socket) ProtoMessage() {}

func (x *ServiceInfoResponse_Socket) ProtoReflect() protoreflect.Message {
	mi := &file_foreverbull_pb_service_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfoResponse_Socket.ProtoReflect.Descriptor instead.
func (*ServiceInfoResponse_Socket) Descriptor() ([]byte, []int) {
	return file_foreverbull_pb_service_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ServiceInfoResponse_Socket) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServiceInfoResponse_Socket) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Algorithm_NamespaceDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataType  string `protobuf:"bytes,1,opt,name=dataType,proto3" json:"dataType,omitempty"`
	ValueType string `protobuf:"bytes,2,opt,name=valueType,proto3" json:"valueType,omitempty"`
}

func (x *Algorithm_NamespaceDefinition) Reset() {
	*x = Algorithm_NamespaceDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foreverbull_pb_service_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Algorithm_NamespaceDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Algorithm_NamespaceDefinition) ProtoMessage() {}

func (x *Algorithm_NamespaceDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_foreverbull_pb_service_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Algorithm_NamespaceDefinition.ProtoReflect.Descriptor instead.
func (*Algorithm_NamespaceDefinition) Descriptor() ([]byte, []int) {
	return file_foreverbull_pb_service_service_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Algorithm_NamespaceDefinition) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *Algorithm_NamespaceDefinition) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

type Algorithm_Namespace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        string                         `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Definition *Algorithm_NamespaceDefinition `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
}

func (x *Algorithm_Namespace) Reset() {
	*x = Algorithm_Namespace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foreverbull_pb_service_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Algorithm_Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Algorithm_Namespace) ProtoMessage() {}

func (x *Algorithm_Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_foreverbull_pb_service_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Algorithm_Namespace.ProtoReflect.Descriptor instead.
func (*Algorithm_Namespace) Descriptor() ([]byte, []int) {
	return file_foreverbull_pb_service_service_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Algorithm_Namespace) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Algorithm_Namespace) GetDefinition() *Algorithm_NamespaceDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type Algorithm_FunctionParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key          string  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	DefaultValue *string `protobuf:"bytes,2,opt,name=defaultValue,proto3,oneof" json:"defaultValue,omitempty"`
	Value        *string `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
	ValueType    string  `protobuf:"bytes,4,opt,name=valueType,proto3" json:"valueType,omitempty"`
}

func (x *Algorithm_FunctionParameter) Reset() {
	*x = Algorithm_FunctionParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foreverbull_pb_service_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Algorithm_FunctionParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Algorithm_FunctionParameter) ProtoMessage() {}

func (x *Algorithm_FunctionParameter) ProtoReflect() protoreflect.Message {
	mi := &file_foreverbull_pb_service_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Algorithm_FunctionParameter.ProtoReflect.Descriptor instead.
func (*Algorithm_FunctionParameter) Descriptor() ([]byte, []int) {
	return file_foreverbull_pb_service_service_proto_rawDescGZIP(), []int{3, 2}
}

func (x *Algorithm_FunctionParameter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Algorithm_FunctionParameter) GetDefaultValue() string {
	if x != nil && x.DefaultValue != nil {
		return *x.DefaultValue
	}
	return ""
}

func (x *Algorithm_FunctionParameter) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *Algorithm_FunctionParameter) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

type Algorithm_Function struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name              string                         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parameters        []*Algorithm_FunctionParameter `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
	ParallelExecution bool                           `protobuf:"varint,3,opt,name=parallelExecution,proto3" json:"parallelExecution,omitempty"`
	RunFirst          bool                           `protobuf:"varint,4,opt,name=runFirst,proto3" json:"runFirst,omitempty"`
	RunLast           bool                           `protobuf:"varint,5,opt,name=runLast,proto3" json:"runLast,omitempty"`
}

func (x *Algorithm_Function) Reset() {
	*x = Algorithm_Function{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foreverbull_pb_service_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Algorithm_Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Algorithm_Function) ProtoMessage() {}

func (x *Algorithm_Function) ProtoReflect() protoreflect.Message {
	mi := &file_foreverbull_pb_service_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Algorithm_Function.ProtoReflect.Descriptor instead.
func (*Algorithm_Function) Descriptor() ([]byte, []int) {
	return file_foreverbull_pb_service_service_proto_rawDescGZIP(), []int{3, 3}
}

func (x *Algorithm_Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Algorithm_Function) GetParameters() []*Algorithm_FunctionParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Algorithm_Function) GetParallelExecution() bool {
	if x != nil {
		return x.ParallelExecution
	}
	return false
}

func (x *Algorithm_Function) GetRunFirst() bool {
	if x != nil {
		return x.RunFirst
	}
	return false
}

func (x *Algorithm_Function) GetRunLast() bool {
	if x != nil {
		return x.RunLast
	}
	return false
}

type ConfigureExecutionRequest_FunctionParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value     string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ValueType string `protobuf:"bytes,3,opt,name=valueType,proto3" json:"valueType,omitempty"`
}

func (x *ConfigureExecutionRequest_FunctionParameter) Reset() {
	*x = ConfigureExecutionRequest_FunctionParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foreverbull_pb_service_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureExecutionRequest_FunctionParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureExecutionRequest_FunctionParameter) ProtoMessage() {}

func (x *ConfigureExecutionRequest_FunctionParameter) ProtoReflect() protoreflect.Message {
	mi := &file_foreverbull_pb_service_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureExecutionRequest_FunctionParameter.ProtoReflect.Descriptor instead.
func (*ConfigureExecutionRequest_FunctionParameter) Descriptor() ([]byte, []int) {
	return file_foreverbull_pb_service_service_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ConfigureExecutionRequest_FunctionParameter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigureExecutionRequest_FunctionParameter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigureExecutionRequest_FunctionParameter) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

type ConfigureExecutionRequest_Function struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string                                         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parameters []*ConfigureExecutionRequest_FunctionParameter `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
}

func (x *ConfigureExecutionRequest_Function) Reset() {
	*x = ConfigureExecutionRequest_Function{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foreverbull_pb_service_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigureExecutionRequest_Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureExecutionRequest_Function) ProtoMessage() {}

func (x *ConfigureExecutionRequest_Function) ProtoReflect() protoreflect.Message {
	mi := &file_foreverbull_pb_service_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureExecutionRequest_Function.ProtoReflect.Descriptor instead.
func (*ConfigureExecutionRequest_Function) Descriptor() ([]byte, []int) {
	return file_foreverbull_pb_service_service_proto_rawDescGZIP(), []int{4, 1}
}

func (x *ConfigureExecutionRequest_Function) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigureExecutionRequest_Function) GetParameters() []*ConfigureExecutionRequest_FunctionParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

var File_foreverbull_pb_service_service_proto protoreflect.FileDescriptor

var file_foreverbull_pb_service_service_proto_rawDesc = []byte{
	0x0a, 0x24, 0x66, 0x6f, 0x72, 0x65, 0x76, 0x65, 0x72, 0x62, 0x75, 0x6c, 0x6c, 0x2f, 0x70, 0x62,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x66, 0x6f, 0x72, 0x65, 0x76, 0x65, 0x72, 0x62,
	0x75, 0x6c, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x24, 0x66,
	0x6f, 0x72, 0x65, 0x76, 0x65, 0x72, 0x62, 0x75, 0x6c, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x66, 0x69,
	0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2f, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xcf, 0x01, 0x0a, 0x13, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x4a, 0x0a, 0x06, 0x73, 0x6f, 0x63, 0x6b, 0x65,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x76, 0x65,
	0x72, 0x62, 0x75, 0x6c, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x73, 0x6f, 0x63,
	0x6b, 0x65, 0x74, 0x1a, 0x30, 0x0a, 0x06, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x3f, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x61, 0x73, 0x6b, 0x12, 0x17, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x65, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x12, 0x17, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x12,
	0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x85, 0x06,
	0x0a, 0x09, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x48, 0x0a, 0x09, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x66, 0x6f,
	0x72, 0x65, 0x76, 0x65, 0x72, 0x62, 0x75, 0x6c, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x2e, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x4b, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x76, 0x65, 0x72,
	0x62, 0x75, 0x6c, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x52, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x1a,
	0x4f, 0x0a, 0x13, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x44, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x1a, 0x74, 0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x55, 0x0a, 0x0a, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x76, 0x65, 0x72, 0x62, 0x75, 0x6c,
	0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x6c, 0x67,
	0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0xa2, 0x01, 0x0a, 0x11, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x27,
	0x0a, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0xd7, 0x01, 0x0a, 0x08,
	0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x53, 0x0a, 0x0a,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x33, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x76, 0x65, 0x72, 0x62, 0x75, 0x6c, 0x6c, 0x2e, 0x70,
	0x62, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69,
	0x74, 0x68, 0x6d, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x73, 0x12, 0x2c, 0x0a, 0x11, 0x70, 0x61, 0x72, 0x61, 0x6c, 0x6c, 0x65, 0x6c, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x70, 0x61,
	0x72, 0x61, 0x6c, 0x6c, 0x65, 0x6c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x75, 0x6e, 0x46, 0x69, 0x72, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x72, 0x75, 0x6e, 0x46, 0x69, 0x72, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x75, 0x6e, 0x4c, 0x61, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x75,
	0x6e, 0x4c, 0x61, 0x73, 0x74, 0x22, 0xbe, 0x03, 0x0a, 0x19, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x50, 0x6f, 0x72,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x50,
	0x6f, 0x72, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x50, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x61, 0x74,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x55, 0x52, 0x4c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x55, 0x52, 0x4c, 0x12, 0x58, 0x0a, 0x09, 0x66,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3a,
	0x2e, 0x66, 0x6f, 0x72, 0x65, 0x76, 0x65, 0x72, 0x62, 0x75, 0x6c, 0x6c, 0x2e, 0x70, 0x62, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72,
	0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x59, 0x0a, 0x11, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x1a, 0x83, 0x01, 0x0a, 0x08, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x63, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x43, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x76, 0x65, 0x72, 0x62,
	0x75, 0x6c, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x22, 0x1c, 0x0a, 0x1a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x65, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0xb8, 0x01, 0x0a, 0x0d, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x12, 0x3f,
	0x0a, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x76, 0x65, 0x72, 0x62, 0x75, 0x6c, 0x6c, 0x2e,
	0x70, 0x62, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x66,
	0x6f, 0x6c, 0x69, 0x6f, 0x52, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x22,
	0x80, 0x01, 0x0a, 0x0e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x12, 0x35, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x76, 0x65, 0x72,
	0x62, 0x75, 0x6c, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x66, 0x69, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x19, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0xa4, 0x01, 0x0a, 0x10, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x40, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x66, 0x6f, 0x72, 0x65, 0x76, 0x65,
	0x72, 0x62, 0x75, 0x6c, 0x6c, 0x2e, 0x70, 0x62, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x42,
	0x08, 0x0a, 0x06, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x76, 0x0a, 0x11, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x01, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a,
	0x06, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x2a, 0x28, 0x0a, 0x14, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45, 0x54,
	0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x45, 0x54, 0x10, 0x01, 0x42, 0x37, 0x5a, 0x35, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x68, 0x6a, 0x6e, 0x69, 0x6c,
	0x73, 0x73, 0x6f, 0x6e, 0x2f, 0x66, 0x6f, 0x72, 0x65, 0x76, 0x65, 0x72, 0x62, 0x75, 0x6c, 0x6c,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_foreverbull_pb_service_service_proto_rawDescOnce sync.Once
	file_foreverbull_pb_service_service_proto_rawDescData = file_foreverbull_pb_service_service_proto_rawDesc
)

func file_foreverbull_pb_service_service_proto_rawDescGZIP() []byte {
	file_foreverbull_pb_service_service_proto_rawDescOnce.Do(func() {
		file_foreverbull_pb_service_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_foreverbull_pb_service_service_proto_rawDescData)
	})
	return file_foreverbull_pb_service_service_proto_rawDescData
}

var file_foreverbull_pb_service_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_foreverbull_pb_service_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_foreverbull_pb_service_service_proto_goTypes = []any{
	(NamespaceRequestType)(0),                           // 0: foreverbull.pb.service.NamespaceRequestType
	(*ServiceInfoResponse)(nil),                         // 1: foreverbull.pb.service.ServiceInfoResponse
	(*Request)(nil),                                     // 2: foreverbull.pb.service.Request
	(*Response)(nil),                                    // 3: foreverbull.pb.service.Response
	(*Algorithm)(nil),                                   // 4: foreverbull.pb.service.Algorithm
	(*ConfigureExecutionRequest)(nil),                   // 5: foreverbull.pb.service.ConfigureExecutionRequest
	(*ConfigureExecutionResponse)(nil),                  // 6: foreverbull.pb.service.ConfigureExecutionResponse
	(*WorkerRequest)(nil),                               // 7: foreverbull.pb.service.WorkerRequest
	(*WorkerResponse)(nil),                              // 8: foreverbull.pb.service.WorkerResponse
	(*NamespaceRequest)(nil),                            // 9: foreverbull.pb.service.NamespaceRequest
	(*NamespaceResponse)(nil),                           // 10: foreverbull.pb.service.NamespaceResponse
	(*ServiceInfoResponse_Socket)(nil),                  // 11: foreverbull.pb.service.ServiceInfoResponse.Socket
	(*Algorithm_NamespaceDefinition)(nil),               // 12: foreverbull.pb.service.Algorithm.NamespaceDefinition
	(*Algorithm_Namespace)(nil),                         // 13: foreverbull.pb.service.Algorithm.Namespace
	(*Algorithm_FunctionParameter)(nil),                 // 14: foreverbull.pb.service.Algorithm.FunctionParameter
	(*Algorithm_Function)(nil),                          // 15: foreverbull.pb.service.Algorithm.Function
	(*ConfigureExecutionRequest_FunctionParameter)(nil), // 16: foreverbull.pb.service.ConfigureExecutionRequest.FunctionParameter
	(*ConfigureExecutionRequest_Function)(nil),          // 17: foreverbull.pb.service.ConfigureExecutionRequest.Function
	(*timestamppb.Timestamp)(nil),                       // 18: google.protobuf.Timestamp
	(*finance.Portfolio)(nil),                           // 19: foreverbull.pb.finance.Portfolio
	(*finance.Order)(nil),                               // 20: foreverbull.pb.finance.Order
	(*structpb.Struct)(nil),                             // 21: google.protobuf.Struct
}
var file_foreverbull_pb_service_service_proto_depIdxs = []int32{
	11, // 0: foreverbull.pb.service.ServiceInfoResponse.socket:type_name -> foreverbull.pb.service.ServiceInfoResponse.Socket
	15, // 1: foreverbull.pb.service.Algorithm.functions:type_name -> foreverbull.pb.service.Algorithm.Function
	13, // 2: foreverbull.pb.service.Algorithm.namespaces:type_name -> foreverbull.pb.service.Algorithm.Namespace
	17, // 3: foreverbull.pb.service.ConfigureExecutionRequest.functions:type_name -> foreverbull.pb.service.ConfigureExecutionRequest.Function
	18, // 4: foreverbull.pb.service.WorkerRequest.timestamp:type_name -> google.protobuf.Timestamp
	19, // 5: foreverbull.pb.service.WorkerRequest.portfolio:type_name -> foreverbull.pb.finance.Portfolio
	20, // 6: foreverbull.pb.service.WorkerResponse.orders:type_name -> foreverbull.pb.finance.Order
	0,  // 7: foreverbull.pb.service.NamespaceRequest.type:type_name -> foreverbull.pb.service.NamespaceRequestType
	21, // 8: foreverbull.pb.service.NamespaceRequest.value:type_name -> google.protobuf.Struct
	21, // 9: foreverbull.pb.service.NamespaceResponse.value:type_name -> google.protobuf.Struct
	12, // 10: foreverbull.pb.service.Algorithm.Namespace.definition:type_name -> foreverbull.pb.service.Algorithm.NamespaceDefinition
	14, // 11: foreverbull.pb.service.Algorithm.Function.parameters:type_name -> foreverbull.pb.service.Algorithm.FunctionParameter
	16, // 12: foreverbull.pb.service.ConfigureExecutionRequest.Function.parameters:type_name -> foreverbull.pb.service.ConfigureExecutionRequest.FunctionParameter
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_foreverbull_pb_service_service_proto_init() }
func file_foreverbull_pb_service_service_proto_init() {
	if File_foreverbull_pb_service_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_foreverbull_pb_service_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ServiceInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foreverbull_pb_service_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foreverbull_pb_service_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foreverbull_pb_service_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Algorithm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foreverbull_pb_service_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigureExecutionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foreverbull_pb_service_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigureExecutionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foreverbull_pb_service_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*WorkerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foreverbull_pb_service_service_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*WorkerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foreverbull_pb_service_service_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*NamespaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foreverbull_pb_service_service_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*NamespaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foreverbull_pb_service_service_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ServiceInfoResponse_Socket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foreverbull_pb_service_service_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*Algorithm_NamespaceDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foreverbull_pb_service_service_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*Algorithm_Namespace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foreverbull_pb_service_service_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*Algorithm_FunctionParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foreverbull_pb_service_service_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*Algorithm_Function); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foreverbull_pb_service_service_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigureExecutionRequest_FunctionParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foreverbull_pb_service_service_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigureExecutionRequest_Function); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_foreverbull_pb_service_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_foreverbull_pb_service_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_foreverbull_pb_service_service_proto_msgTypes[7].OneofWrappers = []any{}
	file_foreverbull_pb_service_service_proto_msgTypes[8].OneofWrappers = []any{}
	file_foreverbull_pb_service_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_foreverbull_pb_service_service_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_foreverbull_pb_service_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_foreverbull_pb_service_service_proto_goTypes,
		DependencyIndexes: file_foreverbull_pb_service_service_proto_depIdxs,
		EnumInfos:         file_foreverbull_pb_service_service_proto_enumTypes,
		MessageInfos:      file_foreverbull_pb_service_service_proto_msgTypes,
	}.Build()
	File_foreverbull_pb_service_service_proto = out.File
	file_foreverbull_pb_service_service_proto_rawDesc = nil
	file_foreverbull_pb_service_service_proto_goTypes = nil
	file_foreverbull_pb_service_service_proto_depIdxs = nil
}
