// Code generated by mockery v2.46.3. DO NOT EDIT.

package pb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeHealthServer is an autogenerated mock type for the UnsafeHealthServer type
type MockUnsafeHealthServer struct {
	mock.Mock
}

// mustEmbedUnimplementedHealthServer provides a mock function with given fields:
func (_m *MockUnsafeHealthServer) mustEmbedUnimplementedHealthServer() {
	_m.Called()
}

// NewMockUnsafeHealthServer creates a new instance of MockUnsafeHealthServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeHealthServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeHealthServer {
	mock := &MockUnsafeHealthServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
