// Code generated by mockery v2.50.1. DO NOT EDIT.

package pb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeWorkerServer is an autogenerated mock type for the UnsafeWorkerServer type
type MockUnsafeWorkerServer struct {
	mock.Mock
}

// mustEmbedUnimplementedWorkerServer provides a mock function with no fields
func (_m *MockUnsafeWorkerServer) mustEmbedUnimplementedWorkerServer() {
	_m.Called()
}

// NewMockUnsafeWorkerServer creates a new instance of MockUnsafeWorkerServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeWorkerServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeWorkerServer {
	mock := &MockUnsafeWorkerServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
