// Code generated by mockery v2.18.0. DO NOT EDIT.

package mocks

import (
	context "context"

	engine "github.com/lhjnilsson/foreverbull/pkg/backtest/engine"
	entity "github.com/lhjnilsson/foreverbull/pkg/backtest/entity"

	mock "github.com/stretchr/testify/mock"
)

// Engine is an autogenerated mock type for the Engine type
type Engine struct {
	mock.Mock
}

// CancelOrder provides a mock function with given fields: order
func (_m *Engine) CancelOrder(order *engine.Order) error {
	ret := _m.Called(order)

	var r0 error
	if rf, ok := ret.Get(0).(func(*engine.Order) error); ok {
		r0 = rf(order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfigureExecution provides a mock function with given fields: _a0, _a1
func (_m *Engine) ConfigureExecution(_a0 context.Context, _a1 *entity.Execution) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Execution) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Continue provides a mock function with given fields:
func (_m *Engine) Continue() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DownloadIngestion provides a mock function with given fields: _a0, _a1
func (_m *Engine) DownloadIngestion(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetExecutionResult provides a mock function with given fields: executionID
func (_m *Engine) GetExecutionResult(executionID string) (*engine.Result, error) {
	ret := _m.Called(executionID)

	var r0 *engine.Result
	if rf, ok := ret.Get(0).(func(string) *engine.Result); ok {
		r0 = rf(executionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*engine.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(executionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMessage provides a mock function with given fields:
func (_m *Engine) GetMessage() (*engine.Period, error) {
	ret := _m.Called()

	var r0 *engine.Period
	if rf, ok := ret.Get(0).(func() *engine.Period); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*engine.Period)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrder provides a mock function with given fields: _a0
func (_m *Engine) GetOrder(_a0 *engine.Order) (*engine.Order, error) {
	ret := _m.Called(_a0)

	var r0 *engine.Order
	if rf, ok := ret.Get(0).(func(*engine.Order) *engine.Order); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*engine.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*engine.Order) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ingest provides a mock function with given fields: _a0, _a1
func (_m *Engine) Ingest(_a0 context.Context, _a1 *entity.Ingestion) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Ingestion) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Order provides a mock function with given fields: _a0
func (_m *Engine) Order(_a0 *engine.Order) (*engine.Order, error) {
	ret := _m.Called(_a0)

	var r0 *engine.Order
	if rf, ok := ret.Get(0).(func(*engine.Order) *engine.Order); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*engine.Order)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*engine.Order) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RunExecution provides a mock function with given fields: _a0
func (_m *Engine) RunExecution(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields: _a0
func (_m *Engine) Stop(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadIngestion provides a mock function with given fields: _a0, _a1
func (_m *Engine) UploadIngestion(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewEngine interface {
	mock.TestingT
	Cleanup(func())
}

// NewEngine creates a new instance of Engine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEngine(t mockConstructorTestingTNewEngine) *Engine {
	mock := &Engine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
