# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: finance.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 5, 27, 1, "", "finance.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rfinance.proto\x12\x13\x66oreverbull.finance\x1a\x1fgoogle/protobuf/timestamp.proto"X\n\x08Position\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08\x65xchange\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x0c\n\x04\x63ost\x18\x04 \x01(\x01\x12\x0c\n\x04side\x18\x05 \x01(\t"Z\n\tPortfolio\x12\x0c\n\x04\x63\x61sh\x18\x01 \x01(\x01\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x30\n\tpositions\x18\x03 \x03(\x0b\x32\x1d.foreverbull.finance.Position"\xe2\x01\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\x12\x0e\n\x06\x66illed\x18\x04 \x01(\x05\x12\x12\n\ncommission\x18\x05 \x01(\x01\x12\x13\n\x0blimit_price\x18\x06 \x01(\x01\x12\x12\n\nstop_price\x18\x07 \x01(\x01\x12.\n\ncreated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x06status\x18\t \x01(\x0e\x32 .foreverbull.finance.OrderStatus*I\n\x0bOrderStatus\x12\x08\n\x04OPEN\x10\x00\x12\n\n\x06\x46ILLED\x10\x01\x12\x0c\n\x08\x43\x41NCELED\x10\x02\x12\x0c\n\x08REJECTED\x10\x03\x12\x08\n\x04HELD\x10\x04\x42\nZ\x08./pb_genb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "finance_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\010./pb_gen"
    _globals["_ORDERSTATUS"]._serialized_start = 482
    _globals["_ORDERSTATUS"]._serialized_end = 555
    _globals["_POSITION"]._serialized_start = 71
    _globals["_POSITION"]._serialized_end = 159
    _globals["_PORTFOLIO"]._serialized_start = 161
    _globals["_PORTFOLIO"]._serialized_end = 251
    _globals["_ORDER"]._serialized_start = 254
    _globals["_ORDER"]._serialized_end = 480
# @@protoc_insertion_point(module_scope)
