apiVersion: 1

datasources:
  - name: 'foreverbull'
    type: 'lhjnilsson-foreverbull-datasource'
    access: proxy
    isDefault: false
    orgId: 1
    version: 1
    editable: true
    jsonData:
      path: ''
    secureJsonData:
      apiKey: 'api-key'
