// Code generated by mockery v2.46.3. DO NOT EDIT.

package finance

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMarketdataServer is an autogenerated mock type for the MarketdataServer type
type MockMarketdataServer struct {
	mock.Mock
}

// DownloadHistoricalData provides a mock function with given fields: _a0, _a1
func (_m *MockMarketdataServer) DownloadHistoricalData(_a0 context.Context, _a1 *DownloadHistoricalDataRequest) (*DownloadHistoricalDataResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DownloadHistoricalData")
	}

	var r0 *DownloadHistoricalDataResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *DownloadHistoricalDataRequest) (*DownloadHistoricalDataResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *DownloadHistoricalDataRequest) *DownloadHistoricalDataResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DownloadHistoricalDataResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *DownloadHistoricalDataRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAsset provides a mock function with given fields: _a0, _a1
func (_m *MockMarketdataServer) GetAsset(_a0 context.Context, _a1 *GetAssetRequest) (*GetAssetResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetAsset")
	}

	var r0 *GetAssetResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetAssetRequest) (*GetAssetResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetAssetRequest) *GetAssetResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetAssetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetAssetRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetIndex provides a mock function with given fields: _a0, _a1
func (_m *MockMarketdataServer) GetIndex(_a0 context.Context, _a1 *GetIndexRequest) (*GetIndexResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetIndex")
	}

	var r0 *GetIndexResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetIndexRequest) (*GetIndexResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetIndexRequest) *GetIndexResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetIndexResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetIndexRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedMarketdataServer provides a mock function with given fields:
func (_m *MockMarketdataServer) mustEmbedUnimplementedMarketdataServer() {
	_m.Called()
}

// NewMockMarketdataServer creates a new instance of MockMarketdataServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMarketdataServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMarketdataServer {
	mock := &MockMarketdataServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
