// Code generated by mockery v2.18.0. DO NOT EDIT.

package pb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeFinanceServer is an autogenerated mock type for the UnsafeFinanceServer type
type MockUnsafeFinanceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedFinanceServer provides a mock function with given fields:
func (_m *MockUnsafeFinanceServer) mustEmbedUnimplementedFinanceServer() {
	_m.Called()
}

type mockConstructorTestingTNewMockUnsafeFinanceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUnsafeFinanceServer creates a new instance of MockUnsafeFinanceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUnsafeFinanceServer(t mockConstructorTestingTNewMockUnsafeFinanceServer) *MockUnsafeFinanceServer {
	mock := &MockUnsafeFinanceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
