// Code generated by mockery v2.18.0. DO NOT EDIT.

package engine

import (
	context "context"

	backtest "github.com/lhjnilsson/foreverbull/internal/pb/backtest"

	entity "github.com/lhjnilsson/foreverbull/pkg/backtest/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockEngine is an autogenerated mock type for the Engine type
type MockEngine struct {
	mock.Mock
}

// ConfigureExecution provides a mock function with given fields: _a0, _a1
func (_m *MockEngine) ConfigureExecution(_a0 context.Context, _a1 *entity.Execution) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Execution) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Continue provides a mock function with given fields: _a0
func (_m *MockEngine) Continue(_a0 *[]Order) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*[]Order) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DownloadIngestion provides a mock function with given fields: _a0, _a1
func (_m *MockEngine) DownloadIngestion(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetExecutionResult provides a mock function with given fields: executionID
func (_m *MockEngine) GetExecutionResult(executionID string) (*Result, error) {
	ret := _m.Called(executionID)

	var r0 *Result
	if rf, ok := ret.Get(0).(func(string) *Result); ok {
		r0 = rf(executionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(executionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPortfolio provides a mock function with given fields:
func (_m *MockEngine) GetPortfolio() (*backtest.GetPortfolioResponse, error) {
	ret := _m.Called()

	var r0 *backtest.GetPortfolioResponse
	if rf, ok := ret.Get(0).(func() *backtest.GetPortfolioResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*backtest.GetPortfolioResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Ingest provides a mock function with given fields: _a0, _a1
func (_m *MockEngine) Ingest(_a0 context.Context, _a1 *entity.Ingestion) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Ingestion) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RunExecution provides a mock function with given fields: _a0
func (_m *MockEngine) RunExecution(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields: _a0
func (_m *MockEngine) Stop(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadIngestion provides a mock function with given fields: _a0, _a1
func (_m *MockEngine) UploadIngestion(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMockEngine interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockEngine creates a new instance of MockEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockEngine(t mockConstructorTestingTNewMockEngine) *MockEngine {
	mock := &MockEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
