"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import foreverbull.pb.finance.finance_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class IngestRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_DATE_FIELD_NUMBER: builtins.int
    END_DATE_FIELD_NUMBER: builtins.int
    SYMBOLS_FIELD_NUMBER: builtins.int
    @property
    def start_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def end_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def symbols(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        start_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        symbols: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["end_date", b"end_date", "start_date", b"start_date"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["end_date", b"end_date", "start_date", b"start_date", "symbols", b"symbols"]
    ) -> None: ...

global___IngestRequest = IngestRequest

@typing.final
class IngestResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_DATE_FIELD_NUMBER: builtins.int
    END_DATE_FIELD_NUMBER: builtins.int
    SYMBOLS_FIELD_NUMBER: builtins.int
    @property
    def start_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def end_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def symbols(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        start_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        symbols: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["end_date", b"end_date", "start_date", b"start_date"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["end_date", b"end_date", "start_date", b"start_date", "symbols", b"symbols"]
    ) -> None: ...

global___IngestResponse = IngestResponse

@typing.final
class ConfigureRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_DATE_FIELD_NUMBER: builtins.int
    END_DATE_FIELD_NUMBER: builtins.int
    SYMBOLS_FIELD_NUMBER: builtins.int
    BENCHMARK_FIELD_NUMBER: builtins.int
    benchmark: builtins.str
    @property
    def start_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def end_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def symbols(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        start_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        symbols: collections.abc.Iterable[builtins.str] | None = ...,
        benchmark: builtins.str | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_benchmark", b"_benchmark", "benchmark", b"benchmark", "end_date", b"end_date", "start_date", b"start_date"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_benchmark",
            b"_benchmark",
            "benchmark",
            b"benchmark",
            "end_date",
            b"end_date",
            "start_date",
            b"start_date",
            "symbols",
            b"symbols",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_benchmark", b"_benchmark"]
    ) -> typing.Literal["benchmark"] | None: ...

global___ConfigureRequest = ConfigureRequest

@typing.final
class ConfigureResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_DATE_FIELD_NUMBER: builtins.int
    END_DATE_FIELD_NUMBER: builtins.int
    SYMBOLS_FIELD_NUMBER: builtins.int
    BENCHMARK_FIELD_NUMBER: builtins.int
    benchmark: builtins.str
    @property
    def start_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def end_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def symbols(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        start_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        symbols: collections.abc.Iterable[builtins.str] | None = ...,
        benchmark: builtins.str | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_benchmark", b"_benchmark", "benchmark", b"benchmark", "end_date", b"end_date", "start_date", b"start_date"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_benchmark",
            b"_benchmark",
            "benchmark",
            b"benchmark",
            "end_date",
            b"end_date",
            "start_date",
            b"start_date",
            "symbols",
            b"symbols",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_benchmark", b"_benchmark"]
    ) -> typing.Literal["benchmark"] | None: ...

global___ConfigureResponse = ConfigureResponse

@typing.final
class Position(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    COST_BASIS_FIELD_NUMBER: builtins.int
    LAST_SALE_PRICE_FIELD_NUMBER: builtins.int
    LAST_SALE_DATE_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    amount: builtins.int
    cost_basis: builtins.float
    last_sale_price: builtins.float
    @property
    def last_sale_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
        amount: builtins.int = ...,
        cost_basis: builtins.float = ...,
        last_sale_price: builtins.float = ...,
        last_sale_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["last_sale_date", b"last_sale_date"]) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "amount",
            b"amount",
            "cost_basis",
            b"cost_basis",
            "last_sale_date",
            b"last_sale_date",
            "last_sale_price",
            b"last_sale_price",
            "symbol",
            b"symbol",
        ],
    ) -> None: ...

global___Position = Position

@typing.final
class GetPortfolioResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    CASH_FLOW_FIELD_NUMBER: builtins.int
    STARTING_CASH_FIELD_NUMBER: builtins.int
    PORTFOLIO_VALUE_FIELD_NUMBER: builtins.int
    PNL_FIELD_NUMBER: builtins.int
    RETURNS_FIELD_NUMBER: builtins.int
    CASH_FIELD_NUMBER: builtins.int
    POSITION_VALUE_FIELD_NUMBER: builtins.int
    POSITION_EXPOSURE_FIELD_NUMBER: builtins.int
    POSITIONS_FIELD_NUMBER: builtins.int
    cash_flow: builtins.float
    starting_cash: builtins.float
    portfolio_value: builtins.float
    pnl: builtins.float
    returns: builtins.float
    cash: builtins.float
    position_value: builtins.float
    position_exposure: builtins.float
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def positions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Position]: ...
    def __init__(
        self,
        *,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        cash_flow: builtins.float = ...,
        starting_cash: builtins.float = ...,
        portfolio_value: builtins.float = ...,
        pnl: builtins.float = ...,
        returns: builtins.float = ...,
        cash: builtins.float = ...,
        position_value: builtins.float = ...,
        position_exposure: builtins.float = ...,
        positions: collections.abc.Iterable[global___Position] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "cash",
            b"cash",
            "cash_flow",
            b"cash_flow",
            "pnl",
            b"pnl",
            "portfolio_value",
            b"portfolio_value",
            "position_exposure",
            b"position_exposure",
            "position_value",
            b"position_value",
            "positions",
            b"positions",
            "returns",
            b"returns",
            "starting_cash",
            b"starting_cash",
            "timestamp",
            b"timestamp",
        ],
    ) -> None: ...

global___GetPortfolioResponse = GetPortfolioResponse

@typing.final
class Order(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: builtins.int
    AMOUNT_FIELD_NUMBER: builtins.int
    symbol: builtins.str
    amount: builtins.int
    def __init__(
        self,
        *,
        symbol: builtins.str = ...,
        amount: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["amount", b"amount", "symbol", b"symbol"]) -> None: ...

global___Order = Order

@typing.final
class ContinueRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ORDERS_FIELD_NUMBER: builtins.int
    @property
    def orders(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Order]: ...
    def __init__(
        self,
        *,
        orders: collections.abc.Iterable[global___Order] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["orders", b"orders"]) -> None: ...

global___ContinueRequest = ContinueRequest

@typing.final
class Period(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    PNL_FIELD_NUMBER: builtins.int
    RETURNS_FIELD_NUMBER: builtins.int
    PORTFOLIO_VALUE_FIELD_NUMBER: builtins.int
    LONGS_COUNT_FIELD_NUMBER: builtins.int
    SHORTS_COUNT_FIELD_NUMBER: builtins.int
    LONG_VALUE_FIELD_NUMBER: builtins.int
    SHORT_VALUE_FIELD_NUMBER: builtins.int
    STARTING_EXPOSURE_FIELD_NUMBER: builtins.int
    ENDING_EXPOSURE_FIELD_NUMBER: builtins.int
    LONG_EXPOSURE_FIELD_NUMBER: builtins.int
    SHORT_EXPOSURE_FIELD_NUMBER: builtins.int
    CAPITAL_USED_FIELD_NUMBER: builtins.int
    GROSS_LEVERAGE_FIELD_NUMBER: builtins.int
    NET_LEVERAGE_FIELD_NUMBER: builtins.int
    STARTING_VALUE_FIELD_NUMBER: builtins.int
    ENDING_VALUE_FIELD_NUMBER: builtins.int
    STARTING_CASH_FIELD_NUMBER: builtins.int
    ENDING_CASH_FIELD_NUMBER: builtins.int
    MAX_DRAWDOWN_FIELD_NUMBER: builtins.int
    MAX_LEVERAGE_FIELD_NUMBER: builtins.int
    EXCESS_RETURN_FIELD_NUMBER: builtins.int
    TREASURY_PERIOD_RETURN_FIELD_NUMBER: builtins.int
    ALGORITHM_PERIOD_RETURN_FIELD_NUMBER: builtins.int
    ALGO_VOLATILITY_FIELD_NUMBER: builtins.int
    SHARPE_FIELD_NUMBER: builtins.int
    SORTINO_FIELD_NUMBER: builtins.int
    BENCHMARK_PERIOD_RETURN_FIELD_NUMBER: builtins.int
    BENCHMARK_VOLATILITY_FIELD_NUMBER: builtins.int
    ALPHA_FIELD_NUMBER: builtins.int
    BETA_FIELD_NUMBER: builtins.int
    POSITIONS_FIELD_NUMBER: builtins.int
    PNL: builtins.float
    returns: builtins.float
    portfolio_value: builtins.float
    longs_count: builtins.int
    shorts_count: builtins.int
    long_value: builtins.float
    short_value: builtins.float
    starting_exposure: builtins.float
    ending_exposure: builtins.float
    long_exposure: builtins.float
    short_exposure: builtins.float
    capital_used: builtins.float
    gross_leverage: builtins.float
    net_leverage: builtins.float
    starting_value: builtins.float
    ending_value: builtins.float
    starting_cash: builtins.float
    ending_cash: builtins.float
    max_drawdown: builtins.float
    max_leverage: builtins.float
    excess_return: builtins.float
    treasury_period_return: builtins.float
    algorithm_period_return: builtins.float
    algo_volatility: builtins.float
    sharpe: builtins.float
    sortino: builtins.float
    benchmark_period_return: builtins.float
    benchmark_volatility: builtins.float
    alpha: builtins.float
    beta: builtins.float
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def positions(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        foreverbull.pb.finance.finance_pb2.Position
    ]: ...
    def __init__(
        self,
        *,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        PNL: builtins.float = ...,
        returns: builtins.float = ...,
        portfolio_value: builtins.float = ...,
        longs_count: builtins.int = ...,
        shorts_count: builtins.int = ...,
        long_value: builtins.float = ...,
        short_value: builtins.float = ...,
        starting_exposure: builtins.float = ...,
        ending_exposure: builtins.float = ...,
        long_exposure: builtins.float = ...,
        short_exposure: builtins.float = ...,
        capital_used: builtins.float = ...,
        gross_leverage: builtins.float = ...,
        net_leverage: builtins.float = ...,
        starting_value: builtins.float = ...,
        ending_value: builtins.float = ...,
        starting_cash: builtins.float = ...,
        ending_cash: builtins.float = ...,
        max_drawdown: builtins.float = ...,
        max_leverage: builtins.float = ...,
        excess_return: builtins.float = ...,
        treasury_period_return: builtins.float = ...,
        algorithm_period_return: builtins.float = ...,
        algo_volatility: builtins.float | None = ...,
        sharpe: builtins.float | None = ...,
        sortino: builtins.float | None = ...,
        benchmark_period_return: builtins.float | None = ...,
        benchmark_volatility: builtins.float | None = ...,
        alpha: builtins.float | None = ...,
        beta: builtins.float | None = ...,
        positions: collections.abc.Iterable[foreverbull.pb.finance.finance_pb2.Position] | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_algo_volatility",
            b"_algo_volatility",
            "_alpha",
            b"_alpha",
            "_benchmark_period_return",
            b"_benchmark_period_return",
            "_benchmark_volatility",
            b"_benchmark_volatility",
            "_beta",
            b"_beta",
            "_sharpe",
            b"_sharpe",
            "_sortino",
            b"_sortino",
            "algo_volatility",
            b"algo_volatility",
            "alpha",
            b"alpha",
            "benchmark_period_return",
            b"benchmark_period_return",
            "benchmark_volatility",
            b"benchmark_volatility",
            "beta",
            b"beta",
            "sharpe",
            b"sharpe",
            "sortino",
            b"sortino",
            "timestamp",
            b"timestamp",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "PNL",
            b"PNL",
            "_algo_volatility",
            b"_algo_volatility",
            "_alpha",
            b"_alpha",
            "_benchmark_period_return",
            b"_benchmark_period_return",
            "_benchmark_volatility",
            b"_benchmark_volatility",
            "_beta",
            b"_beta",
            "_sharpe",
            b"_sharpe",
            "_sortino",
            b"_sortino",
            "algo_volatility",
            b"algo_volatility",
            "algorithm_period_return",
            b"algorithm_period_return",
            "alpha",
            b"alpha",
            "benchmark_period_return",
            b"benchmark_period_return",
            "benchmark_volatility",
            b"benchmark_volatility",
            "beta",
            b"beta",
            "capital_used",
            b"capital_used",
            "ending_cash",
            b"ending_cash",
            "ending_exposure",
            b"ending_exposure",
            "ending_value",
            b"ending_value",
            "excess_return",
            b"excess_return",
            "gross_leverage",
            b"gross_leverage",
            "long_exposure",
            b"long_exposure",
            "long_value",
            b"long_value",
            "longs_count",
            b"longs_count",
            "max_drawdown",
            b"max_drawdown",
            "max_leverage",
            b"max_leverage",
            "net_leverage",
            b"net_leverage",
            "portfolio_value",
            b"portfolio_value",
            "positions",
            b"positions",
            "returns",
            b"returns",
            "sharpe",
            b"sharpe",
            "short_exposure",
            b"short_exposure",
            "short_value",
            b"short_value",
            "shorts_count",
            b"shorts_count",
            "sortino",
            b"sortino",
            "starting_cash",
            b"starting_cash",
            "starting_exposure",
            b"starting_exposure",
            "starting_value",
            b"starting_value",
            "timestamp",
            b"timestamp",
            "treasury_period_return",
            b"treasury_period_return",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_algo_volatility", b"_algo_volatility"]
    ) -> typing.Literal["algo_volatility"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_alpha", b"_alpha"]) -> typing.Literal["alpha"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_benchmark_period_return", b"_benchmark_period_return"]
    ) -> typing.Literal["benchmark_period_return"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_benchmark_volatility", b"_benchmark_volatility"]
    ) -> typing.Literal["benchmark_volatility"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_beta", b"_beta"]) -> typing.Literal["beta"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_sharpe", b"_sharpe"]) -> typing.Literal["sharpe"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_sortino", b"_sortino"]) -> typing.Literal["sortino"] | None: ...

global___Period = Period

@typing.final
class ResultResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PERIODS_FIELD_NUMBER: builtins.int
    @property
    def periods(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Period]: ...
    def __init__(
        self,
        *,
        periods: collections.abc.Iterable[global___Period] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["periods", b"periods"]) -> None: ...

global___ResultResponse = ResultResponse

@typing.final
class UploadResultRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXECUTION_FIELD_NUMBER: builtins.int
    execution: builtins.str
    def __init__(
        self,
        *,
        execution: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["execution", b"execution"]) -> None: ...

global___UploadResultRequest = UploadResultRequest
