# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: foreverbull/pb/backtest/service.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 1, "", "foreverbull/pb/backtest/service.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n%foreverbull/pb/backtest/service.proto\x12\x17\x66oreverbull.pb.backtest\x1a\x1fgoogle/protobuf/timestamp.proto"~\n\rIngestRequest\x12.\n\nstart_date\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07symbols\x18\x03 \x03(\t"\x7f\n\x0eIngestResponse\x12.\n\nstart_date\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07symbols\x18\x03 \x03(\t"\xa1\x01\n\nRunRequest\x12.\n\nstart_date\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07symbols\x18\x03 \x03(\t\x12\x16\n\tbenchmark\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_benchmark"\xa2\x01\n\x0bRunResponse\x12.\n\nstart_date\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07symbols\x18\x03 \x03(\t\x12\x16\n\tbenchmark\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_benchmark"\x8d\x01\n\x10NewPeriodRequest\x12?\n\x06orders\x18\x01 \x03(\x0b\x32/.foreverbull.pb.backtest.NewPeriodRequest.Order\x1a\x38\n\x05Order\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x01\x12\r\n\x05price\x18\x03 \x01(\x01"P\n\x11NewPeriodResponse\x1a;\n\x08Position\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x01\x12\r\n\x05price\x18\x03 \x01(\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "foreverbull.pb.backtest.service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_INGESTREQUEST"]._serialized_start = 99
    _globals["_INGESTREQUEST"]._serialized_end = 225
    _globals["_INGESTRESPONSE"]._serialized_start = 227
    _globals["_INGESTRESPONSE"]._serialized_end = 354
    _globals["_RUNREQUEST"]._serialized_start = 357
    _globals["_RUNREQUEST"]._serialized_end = 518
    _globals["_RUNRESPONSE"]._serialized_start = 521
    _globals["_RUNRESPONSE"]._serialized_end = 683
    _globals["_NEWPERIODREQUEST"]._serialized_start = 686
    _globals["_NEWPERIODREQUEST"]._serialized_end = 827
    _globals["_NEWPERIODREQUEST_ORDER"]._serialized_start = 771
    _globals["_NEWPERIODREQUEST_ORDER"]._serialized_end = 827
    _globals["_NEWPERIODRESPONSE"]._serialized_start = 829
    _globals["_NEWPERIODRESPONSE"]._serialized_end = 909
    _globals["_NEWPERIODRESPONSE_POSITION"]._serialized_start = 850
    _globals["_NEWPERIODRESPONSE_POSITION"]._serialized_end = 909
# @@protoc_insertion_point(module_scope)
