"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class IngestRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_DATE_FIELD_NUMBER: builtins.int
    END_DATE_FIELD_NUMBER: builtins.int
    SYMBOLS_FIELD_NUMBER: builtins.int
    @property
    def start_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def end_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def symbols(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        start_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        symbols: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["end_date", b"end_date", "start_date", b"start_date"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["end_date", b"end_date", "start_date", b"start_date", "symbols", b"symbols"]
    ) -> None: ...

global___IngestRequest = IngestRequest

@typing.final
class IngestResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_DATE_FIELD_NUMBER: builtins.int
    END_DATE_FIELD_NUMBER: builtins.int
    SYMBOLS_FIELD_NUMBER: builtins.int
    @property
    def start_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def end_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def symbols(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        start_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        symbols: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["end_date", b"end_date", "start_date", b"start_date"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["end_date", b"end_date", "start_date", b"start_date", "symbols", b"symbols"]
    ) -> None: ...

global___IngestResponse = IngestResponse

@typing.final
class RunRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_DATE_FIELD_NUMBER: builtins.int
    END_DATE_FIELD_NUMBER: builtins.int
    SYMBOLS_FIELD_NUMBER: builtins.int
    BENCHMARK_FIELD_NUMBER: builtins.int
    benchmark: builtins.str
    @property
    def start_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def end_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def symbols(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        start_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        symbols: collections.abc.Iterable[builtins.str] | None = ...,
        benchmark: builtins.str | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_benchmark", b"_benchmark", "benchmark", b"benchmark", "end_date", b"end_date", "start_date", b"start_date"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_benchmark",
            b"_benchmark",
            "benchmark",
            b"benchmark",
            "end_date",
            b"end_date",
            "start_date",
            b"start_date",
            "symbols",
            b"symbols",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_benchmark", b"_benchmark"]
    ) -> typing.Literal["benchmark"] | None: ...

global___RunRequest = RunRequest

@typing.final
class RunResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_DATE_FIELD_NUMBER: builtins.int
    END_DATE_FIELD_NUMBER: builtins.int
    SYMBOLS_FIELD_NUMBER: builtins.int
    BENCHMARK_FIELD_NUMBER: builtins.int
    benchmark: builtins.str
    @property
    def start_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def end_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def symbols(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        start_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        symbols: collections.abc.Iterable[builtins.str] | None = ...,
        benchmark: builtins.str | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_benchmark", b"_benchmark", "benchmark", b"benchmark", "end_date", b"end_date", "start_date", b"start_date"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_benchmark",
            b"_benchmark",
            "benchmark",
            b"benchmark",
            "end_date",
            b"end_date",
            "start_date",
            b"start_date",
            "symbols",
            b"symbols",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_benchmark", b"_benchmark"]
    ) -> typing.Literal["benchmark"] | None: ...

global___RunResponse = RunResponse

@typing.final
class NewPeriodRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Order(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SYMBOL_FIELD_NUMBER: builtins.int
        QUANTITY_FIELD_NUMBER: builtins.int
        PRICE_FIELD_NUMBER: builtins.int
        symbol: builtins.str
        quantity: builtins.float
        price: builtins.float
        def __init__(
            self,
            *,
            symbol: builtins.str = ...,
            quantity: builtins.float = ...,
            price: builtins.float = ...,
        ) -> None: ...
        def ClearField(
            self, field_name: typing.Literal["price", b"price", "quantity", b"quantity", "symbol", b"symbol"]
        ) -> None: ...

    ORDERS_FIELD_NUMBER: builtins.int
    @property
    def orders(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___NewPeriodRequest.Order]: ...
    def __init__(
        self,
        *,
        orders: collections.abc.Iterable[global___NewPeriodRequest.Order] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["orders", b"orders"]) -> None: ...

global___NewPeriodRequest = NewPeriodRequest

@typing.final
class NewPeriodResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Position(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SYMBOL_FIELD_NUMBER: builtins.int
        QUANTITY_FIELD_NUMBER: builtins.int
        PRICE_FIELD_NUMBER: builtins.int
        symbol: builtins.str
        quantity: builtins.float
        price: builtins.float
        def __init__(
            self,
            *,
            symbol: builtins.str = ...,
            quantity: builtins.float = ...,
            price: builtins.float = ...,
        ) -> None: ...
        def ClearField(
            self, field_name: typing.Literal["price", b"price", "quantity", b"quantity", "symbol", b"symbol"]
        ) -> None: ...

    def __init__(
        self,
    ) -> None: ...

global___NewPeriodResponse = NewPeriodResponse
