name: "Weekday trading"

on:
  schedule:
    - cron: "0 20 * * 1-5" # Runs at 20:00 UTC on every weekday

jobs:
  place-orders-to-alpaca:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "new-json-file.json"
          json: ${{ vars.UNIVERSE }}

      - name: Install latest foreverbull
        run: |
          pip install foreverbull
          pip install foreverbull-cli
      - name: Setup environment
        run: |
          foreverbull setup
          foreverbull-cli setup
