name: "on commit jobs"
on:
  push:
    branches-ignore:
      - main

jobs:
  lint-unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      #- name: Build
      #  run: go build -v ./...
      - name: Test
        working-directory: ./pkg/finance/internal/suppliers/marketdata
        run: go test -v ./...
        #run: go test $(go list ./... | grep -v /tests/) -coverprofile=coverage.out -covermode=atomic -timeout 180s
        #env:
        #  DISABLE_LOKI_LOGGING: true
