name: release
on: push
permissions: read-all

jobs:
  release_docker_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push client
        uses: docker/build-push-action@v5
        with:
          context: external/client/python
          file: ./external/client/python/Dockerfile
          build-args: ALGO_FILE=example.py
          platforms: linux/amd64,linux/arm64
          push: true
          tags: lhjnilsson/client-example:latest
      - name: Build and push zipline
        uses: docker/build-push-action@v5
        with:
          context: external/client/python
          file: ./external/client/python/zipline.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: lhjnilsson/zipline:latest

  release_docker_go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push foreverbull
        uses: docker/build-push-action@v5
        with:
          file: ./docker/release.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: lhjnilsson/foreverbull:latest

  release_pypi:
    needs: [release_docker_python, release_docker_go]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Build and push client
        run: |
          cd external/client/python
          python setup.py sdist bdist_wheel
          python -m twine upload --repository pypi dist/*
