name: release
on: push
permissions: read-all

jobs:
  version_tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: version
        run: echo "version=0.0.$(date +"%y%m%d%H%M")" >> "$GITHUB_OUTPUT"

  build_docker_python:
    needs: version_tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push client
        uses: docker/build-push-action@v5
        with:
          context: external/client/python
          file: ./external/client/python/Dockerfile
          build-args: ALGO_FILE=example.py
          platforms: linux/amd64,linux/arm64
          push: true
          tags: lhjnilsson/client-example:${{needs.version_tag.outputs.version}}
      - name: Build and push zipline
        uses: docker/build-push-action@v5
        with:
          context: external/client/python
          file: ./external/client/python/zipline.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: lhjnilsson/zipline:${{needs.version_tag.outputs.version}}

  build_docker_go:
    needs: version_tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push foreverbull
        uses: docker/build-push-action@v5
        with:
          file: ./docker/release.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: lhjnilsson/foreverbull:${{needs.version_tag.outputs.version}}

  build_python_client:
    needs: version_tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip hatch
      - name: Build
        run: |
          cd external/client/python
          hatch version ${{needs.version_tag.outputs.version}}
          hatch build
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: client
          path: external/client/python/dist
          retention-days: 1
