"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import foreverbull.pb.service.service_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class NewExecutionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ALGORITHM_FIELD_NUMBER: builtins.int
    @property
    def algorithm(self) -> foreverbull.pb.service.service_pb2.Algorithm: ...
    def __init__(
        self,
        *,
        algorithm: foreverbull.pb.service.service_pb2.Algorithm | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["algorithm", b"algorithm"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["algorithm", b"algorithm"]) -> None: ...

global___NewExecutionRequest = NewExecutionRequest

@typing.final
class NewExecutionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    START_DATE_FIELD_NUMBER: builtins.int
    END_DATE_FIELD_NUMBER: builtins.int
    SYMBOLS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    id: builtins.str
    error: builtins.str
    @property
    def start_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def end_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def symbols(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        start_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        symbols: collections.abc.Iterable[builtins.str] | None = ...,
        error: builtins.str | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_error", b"_error", "end_date", b"end_date", "error", b"error", "start_date", b"start_date"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_error",
            b"_error",
            "end_date",
            b"end_date",
            "error",
            b"error",
            "id",
            b"id",
            "start_date",
            b"start_date",
            "symbols",
            b"symbols",
        ],
    ) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_error", b"_error"]) -> typing.Literal["error"] | None: ...

global___NewExecutionResponse = NewExecutionResponse

@typing.final
class ConfigureExecutionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXECUTION_FIELD_NUMBER: builtins.int
    START_DATE_FIELD_NUMBER: builtins.int
    END_DATE_FIELD_NUMBER: builtins.int
    SYMBOLS_FIELD_NUMBER: builtins.int
    BENCHMARK_FIELD_NUMBER: builtins.int
    execution: builtins.str
    benchmark: builtins.str
    @property
    def start_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def end_date(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def symbols(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        execution: builtins.str = ...,
        start_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end_date: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        symbols: collections.abc.Iterable[builtins.str] | None = ...,
        benchmark: builtins.str | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_benchmark", b"_benchmark", "benchmark", b"benchmark", "end_date", b"end_date", "start_date", b"start_date"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_benchmark",
            b"_benchmark",
            "benchmark",
            b"benchmark",
            "end_date",
            b"end_date",
            "execution",
            b"execution",
            "start_date",
            b"start_date",
            "symbols",
            b"symbols",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_benchmark", b"_benchmark"]
    ) -> typing.Literal["benchmark"] | None: ...

global___ConfigureExecutionRequest = ConfigureExecutionRequest

@typing.final
class ConfigureExecutionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXECUTION_FIELD_NUMBER: builtins.int
    BROKERPORT_FIELD_NUMBER: builtins.int
    NAMESPACEPORT_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    execution: builtins.str
    brokerPort: builtins.int
    namespacePort: builtins.int
    error: builtins.str
    def __init__(
        self,
        *,
        execution: builtins.str = ...,
        brokerPort: builtins.int = ...,
        namespacePort: builtins.int = ...,
        error: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_error", b"_error", "error", b"error"]) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_error",
            b"_error",
            "brokerPort",
            b"brokerPort",
            "error",
            b"error",
            "execution",
            b"execution",
            "namespacePort",
            b"namespacePort",
        ],
    ) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_error", b"_error"]) -> typing.Literal["error"] | None: ...

global___ConfigureExecutionResponse = ConfigureExecutionResponse

@typing.final
class RunExecutionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXECUTION_FIELD_NUMBER: builtins.int
    execution: builtins.str
    def __init__(
        self,
        *,
        execution: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["execution", b"execution"]) -> None: ...

global___RunExecutionRequest = RunExecutionRequest

@typing.final
class RunExecutionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXECUTION_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    execution: builtins.str
    error: builtins.str
    def __init__(
        self,
        *,
        execution: builtins.str = ...,
        error: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_error", b"_error", "error", b"error"]) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["_error", b"_error", "error", b"error", "execution", b"execution"]
    ) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_error", b"_error"]) -> typing.Literal["error"] | None: ...

global___RunExecutionResponse = RunExecutionResponse
