// Code generated by mockery v2.18.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/lhjnilsson/foreverbull/backtest/entity"
	mock "github.com/stretchr/testify/mock"
)

// Execution is an autogenerated mock type for the Execution type
type Execution struct {
	mock.Mock
}

// Configure provides a mock function with given fields: _a0, _a1
func (_m *Execution) Configure(_a0 context.Context, _a1 *entity.Execution) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Execution) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Run provides a mock function with given fields: _a0, _a1
func (_m *Execution) Run(_a0 context.Context, _a1 *entity.Execution) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Execution) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields: _a0
func (_m *Execution) Stop(_a0 context.Context) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StoreDataFrameAndGetPeriods provides a mock function with given fields: _a0, _a1
func (_m *Execution) StoreDataFrameAndGetPeriods(_a0 context.Context, _a1 string) (*[]entity.Period, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *[]entity.Period
	if rf, ok := ret.Get(0).(func(context.Context, string) *[]entity.Period); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]entity.Period)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewExecution interface {
	mock.TestingT
	Cleanup(func())
}

// NewExecution creates a new instance of Execution. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExecution(t mockConstructorTestingTNewExecution) *Execution {
	mock := &Execution{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
